// src/core/api-docs/swagger-init.ts
import '@/modules/auth/auth.swagger';
import '@/modules/user/user.swagger';
import '@/modules/player/player.swagger';
import '@/modules/organization/organization.swagger';
import '@/modules/team/team.swagger';
import '@/modules/recruitment/recruitment.swagger';
import '@/modules/application/application.swagger';
import '@/modules/notification/notification.swagger';
import '@/modules/chat/chat.swagger';
